services:
  
  smarthome-backend:
    container_name: smarthome-backend
    build: ./backend
    volumes:
      - smarthome-sqlite_data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - jdp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  smarthome-celery-worker:
    container_name: smarthome-celery-worker
    build: ./backend
    command: celery -A config worker --loglevel=info
    volumes:
      - smarthome-sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS: "false"
    depends_on:
      - smarthome-backend
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - jdp-network

  smarthome-celery-beat:
    container_name: smarthome-celery-beat
    build: ./backend
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - smarthome-sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS: "false"
    depends_on:
      - smarthome-backend
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - jdp-network

  smarthome-frontend:
    container_name: smarthome-frontend
    build: ./frontend
    depends_on:
      - smarthome-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - jdp-network
  
  

volumes:
  smarthome-sqlite_data:

networks:
  jdp-network:
    external: true
