# Generated by Django 4.2.29 on 2026-03-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='devices.device')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['-recorded_at'], name='monitoring__recorde_75b165_idx'), models.Index(fields=['device', '-recorded_at'], name='monitoring__device__6960ac_idx')],
            },
        ),
    ]
