# Generated by Django 4.2.29 on 2026-04-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('monitoring', '0002_sensorinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_avg', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('humidity_avg', models.FloatField()),
                ('reading_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_aggregates', to='devices.device')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['device', 'period_type', '-period_start'], name='monitoring__device__fbf33a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sensoraggregate',
            constraint=models.UniqueConstraint(fields=('device', 'period_type', 'period_start'), name='unique_device_period'),
        ),
    ]
