# Generated by Django 4.2.29 on 2026-03-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('timer', 'Timer'), ('recurring', 'Recurring')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.relay')),
            ],
        ),
        migrations.CreateModel(
            name='TimerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='off', max_length=3)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='schedules.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('days_of_week', models.JSONField(help_text='List of day numbers: 0=Monday, 1=Tuesday, ..., 6=Sunday')),
                ('action', models.CharField(choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='off', max_length=3)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='schedules.schedule')),
            ],
        ),
    ]
