# Generated by Django 4.2.29 on 2026-04-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('timer', 'Timer'), ('recurring', 'Recurring'), ('automation', 'Automation')], max_length=10),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_field', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=15)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal')], max_length=3)),
                ('threshold_value', models.FloatField()),
                ('action', models.CharField(choices=[('on', 'Turn On'), ('off', 'Turn Off')], default='off', max_length=3)),
                ('cooldown_minutes', models.PositiveIntegerField(default=5)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='schedules.schedule')),
                ('source_device', models.ForeignKey(help_text='Device whose sensor readings trigger this rule', on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='devices.device')),
            ],
        ),
    ]
