# Generated by Django 4.2.29 on 2026-04-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('schedules', '0002_alter_schedule_schedule_type_automationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='counter_action_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: minutes after trigger to perform reverse action', null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='counter_action_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: minutes after primary action to perform reverse action', null=True),
        ),
        migrations.AddField(
            model_name='timerschedule',
            name='counter_action_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: minutes after primary action to perform reverse action', null=True),
        ),
        migrations.AddField(
            model_name='timerschedule',
            name='counter_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='sensor_field',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('battery', 'Battery')], max_length=15),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='source_device',
            field=models.ForeignKey(blank=True, help_text='Device whose sensor readings trigger this rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='devices.device'),
        ),
    ]
