# Generated by Django 4.2.29 on 2026-04-08 13:32

import apps.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('binary', models.FileField(upload_to=apps.devices.models.firmware_upload_path)),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64)),
                ('release_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='current_firmware_version',
            field=models.CharField(default='0.0.0', max_length=32),
        ),
    ]
