# Generated by Django 5.0 on 2026-04-08 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_firmwareversion_device_current_firmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique device identifier. Auto-generated from MAC for ESP32 devices.', max_length=48, unique=True),
        ),
    ]
